extends RefCounted
class_name GameConstants

const TILE_SIZE := 28
const GRID_COLS := 33
const GRID_ROWS := 33

const BASE_SIZE_TILES := 7
const BASE_GRID_SIZE := 15

const TOWER_COST := 10
const BARRACKS_COST := 20
const MINE_COST := 10
const SLOW_TOWER_COST := 200
const AOE_TOWER_COST := 30
const SNIPER_TOWER_COST := 70
const BOOST_TOWER_COST := 150
const SHOCK_TOWER_COST := 48
const ANTI_AIR_TOWER_COST := 320
const WALL_COST := 50
const HEALING_STATION_COST := 50
const MARKET_COST_EMERALDS := 5
const BOOST_TOWER_RANGE := 220.0

const UNLOCK_WAVE_TOWER := 1
const UNLOCK_WAVE_BARRACKS := 1
const UNLOCK_WAVE_MINE := 1
const UNLOCK_WAVE_AOE := 5
const UNLOCK_WAVE_WALL := 8
const UNLOCK_WAVE_SHOCK := 10
const UNLOCK_WAVE_SNIPER := 12
const UNLOCK_WAVE_BOOST := 15
const UNLOCK_WAVE_HEALING_STATION := 15
const UNLOCK_WAVE_SLOW := 20
const UNLOCK_WAVE_ANTI_AIR := 45
const UNLOCK_WAVE_MARKET := 50

const MINE_DAMAGE := 15.0
const MINE_TRIGGER_RADIUS := 18.0
const MINE_EXPLOSION_RADIUS := 60.0
const MINE_SLOW_DURATION := 1.5
const MINE_SLOW_AMOUNT := 0.4

const MINE_UPGRADE_DAMAGE_COST := 50
const MINE_UPGRADE_DAMAGE_AMOUNT := 10.0
const MINE_UPGRADE_DAMAGE_MAX_LEVEL := 20

const MINE_UPGRADE_RADIUS_COST := 40
const MINE_UPGRADE_RADIUS_AMOUNT := 8.0
const MINE_UPGRADE_RADIUS_MAX_LEVEL := 15

const TOWER_SIZE_GRID := 3
const BARRACKS_SIZE_GRID := 3
const MINE_SIZE_GRID := 1
const SLOW_TOWER_SIZE_GRID := 3
const AOE_TOWER_SIZE_GRID := 3
const SNIPER_TOWER_SIZE_GRID := 3
const BOOST_TOWER_SIZE_GRID := 3
const SHOCK_TOWER_SIZE_GRID := 3
const ANTI_AIR_TOWER_SIZE_GRID := 3
const WALL_SIZE_GRID := 1
const HEALING_STATION_SIZE_GRID := 3
const MARKET_SIZE_GRID := 3

const MAX_TOWERS := 4
const MAX_BARRACKS := 2
const MAX_MINES := 8
const MAX_SLOW_TOWERS := 1
const MAX_AOE_TOWERS := 2
const MAX_SNIPER_TOWERS := 2
const MAX_BOOST_TOWERS := 1
const MAX_SHOCK_TOWERS := 4
const MAX_ANTI_AIR_TOWERS := 2
const MAX_WALLS := 4
const MAX_HEALING_STATIONS := 1
const MAX_MARKETS := 1

const TOWER_RANGE_COST := 15
const TOWER_RATE_COST := 10
const TOWER_DIRS_COST := 40
const TOWER_DMG_COST := 10
const TOWER_FREEZE_COST := 40
const TOWER_FIRE_COST := 40
const TOWER_FREEZE_DURATION := 4.0

const TOWER_FREEZE_SLOW_PERCENT := 0.65
const TOWER_FIRE_DAMAGE_MULTIPLIER := 0.33
const TOWER_FIRE_DURATION := 4.0
const TOWER_DMG_UPGRADE_AMOUNT := 0.7

const BARRACKS_DMG_COST := 15
const BARRACKS_HOLD_COST := 30
const BARRACKS_SPAWN_RATE_COST := 30
const BARRACKS_PROJECTILE_SPEED_COST := 20

const SNIPER_DMG_COST := 30
const SNIPER_RATE_COST := 12

const AOE_DMG_COST := 15
const AOE_RATE_COST := 20
const AOE_AREA_COST := 20
const AOE_AREA_COST_MULTIPLIER := 1.30

const SHOCK_DMG_COST := 15
const SHOCK_RATE_COST := 25
const SHOCK_CHAIN_COST := 30
const SHOCK_CHAIN_COST_MULTIPLIER := 2.5

const SLOW_RANGE_COST := 30
const SLOW_AMOUNT_COST := 40
const SLOW_DURATION_COST := 20
const SLOW_RATE_COST := 15

const BOOST_DMG_COST := 50
const BOOST_RATE_COST := 40

const ANTI_AIR_DMG_COST := 55
const ANTI_AIR_RATE_COST := 50
const ANTI_AIR_RANGE_COST := 65
const ANTI_AIR_MISSILE_COUNT_COST := 0
const ANTI_AIR_EXPLOSION_COST := 0
const ANTI_AIR_CHAIN_COST := 95
const ANTI_AIR_MISSILE_EMERALD_COST := 17
const ANTI_AIR_EXPLOSION_EMERALD_COST := 18

const WAVE_SCALE := 1.045
const INTERMISSION := 12.0
const WAVE_SPAWN_MIN_INTERVAL_FROM_WAVE := 80
const WAVE_SPAWN_MIN_INTERVAL_SECONDS := 0.20
const PATHFINDER_CACHE_MAX_SIZE := 800

const REWARD_SCALE := 1.07
const REWARD_SCALE_SOFT_CAP := 60
const REWARD_SCALE_AFTER_CAP := 1.04
const UPGRADE_COST_MULTIPLIER := 1.20
const WAVE_COMPLETION_BONUS_BASE := 10
const WAVE_COMPLETION_BONUS_PER_WAVE := 2
const WAVE_COMPLETION_BONUS_MAX := 125

const HERO_START_COINS := 0
const HERO_BASE_FIRE_RATE := 1.0
const HERO_BASE_DAMAGE := 0.9

const TOWER_BASE_DAMAGE := 1.1

const COIN_DROP_CHANCE := 0.12
const COIN_MIN_VALUE := 3
const COIN_MAX_VALUE := 20
const COIN_LIFETIME := 15.0

const TALISMAN_DROP_CHANCE := 0.006
const TALISMAN_LIFETIME := 60.0
const TALISMAN_COLLECT_RADIUS := 25.0

const SKILL_COLLECT_COINS_COST := 0
const SKILL_DAMAGE_BOOST_COST := 0
const SKILL_SPEED_BOOST_COST := 0
const SKILL_SLOW_ALL_COST := 0
const SKILL_DAMAGE_BOOST_DURATION := 10.0
const SKILL_SPEED_BOOST_DURATION := 8.0
const SKILL_SLOW_ALL_DURATION := 5.0
const SKILL_SLOW_ALL_AMOUNT := 0.5
const SKILL_DAMAGE_BOOST_MULTIPLIER := 1.5
const SKILL_SPEED_BOOST_MULTIPLIER := 1.3
const SKILL_COLLECT_COINS_COOLDOWN := 60.0
const SKILL_DAMAGE_BOOST_COOLDOWN := 60.0
const SKILL_SPEED_BOOST_COOLDOWN := 60.0
const SKILL_SLOW_ALL_COOLDOWN := 60.0
const SKILL_MAGNETISM_COOLDOWN := 60.0
const SKILL_MAGNETISM_DURATION := 30.0
const COIN_MAGNETISM_RANGE := 20.0

const HERO_ARROW_SPEED := 260.0
const HERO_BASE_HP := 100
const HERO_HOME_MAX_LEVEL := 4
const HERO_HOME_UPGRADE_COST_LEVEL_2 := 1500
const HERO_HOME_UPGRADE_COST_LEVEL_3 := 5500
const HERO_HOME_UPGRADE_COST_LEVEL_4 := 12500
## Multiplicador de dano quando o tiro da base do herói acerta crítico.
const HERO_CRIT_MULTIPLIER_BASE := 2.0
## Chance base de crítico das torres (acumula com talismã de crítico).
const TOWER_CRIT_CHANCE_BASE := 0.05
## Multiplicador de dano quando uma torre acerta crítico (acumula com talismã de dano crítico).
const TOWER_CRIT_MULTIPLIER_BASE := 2.0
const HERO_RANGE_MAX := 9999.0

const COLOR_UI_WHITE := Color(1.0, 1.0, 1.0)
const COLOR_UI_GOLD := Color(1.0, 0.9, 0.3)
const COLOR_UI_RED := Color(1.0, 0.3, 0.3)
const COLOR_UI_GRAY := Color(0.7, 0.7, 0.7)
const COLOR_UI_DARK_BG := Color(0.1, 0.1, 0.15, 0.95)
const COLOR_UI_BORDER := Color(0.3, 0.3, 0.4)
const COLOR_UI_BUTTON_NORMAL := Color(0.2, 0.2, 0.3)
const COLOR_UI_BUTTON_HOVER := Color(0.3, 0.3, 0.4)

const UI_TOP_BAR_HEIGHT := 52.0
const UI_BOTTOM_BAR_HEIGHT := 40.0
const UI_SIDE_PANEL_GAP := 8.0
const UI_RANGE_INDICATOR_SEGMENTS := 64
const UI_MAX_COIN_SOUND_PLAYERS := 3
const UI_TOOLTIP_DELAY := 0.5

const MUSIC_VOLUME_DEFAULT := -7.0

const EFFECT_DAMAGE_NUMBER_DURATION := 1.0
const EFFECT_COIN_COLLECT_DURATION := 0.5
const EFFECT_DEATH_ANIMATION_DURATION := 0.6

const WALL_COST_1ST := 100
const WALL_COST_2ND := 300
const WALL_COST_3RD := 600
const WALL_COST_4TH := 1000

const WALL_BASE_HP := 50.0
const WALL_DAMAGE_RADIUS := 25.0
const WALL_DAMAGE_PER_SECOND := 1.0
const WALL_BOSS_DAMAGE_MULTIPLIER := 2.0
const WALL_UPGRADE_HP_COST := 75
const WALL_UPGRADE_HP_AMOUNT := 25.0
const WALL_MAX_UPGRADES := 5
const TOWER_COST_SCALE_PER_WAVE := 1.02

const TOWER_MIN_FIRE_RATE := 0.50
const SNIPER_MIN_FIRE_RATE := 1.5
const AOE_MIN_FIRE_RATE := 1.8
const SHOCK_MIN_FIRE_RATE := 0.8
const ANTI_AIR_MIN_FIRE_RATE := 0.6
const HERO_MIN_FIRE_RATE := 0.1
## Piso absoluto de cadência quando bônus (talismã, perk, melhoria, prestígio) ultrapassam o cap de upgrade.
const BONUS_MIN_FIRE_RATE := 0.02

const SHOCK_MAX_CHAIN_COUNT := 15
const AOE_MAX_RADIUS := 250.0
const ANTI_AIR_MAX_RANGE := 400.0

const TOWER_FIRE_RATE_REDUCTION := 0.05
const SNIPER_FIRE_RATE_REDUCTION := 0.5
const AOE_FIRE_RATE_REDUCTION := 0.3
const SHOCK_FIRE_RATE_REDUCTION := 0.2
const ANTI_AIR_FIRE_RATE_REDUCTION := 0.25
const HERO_FIRE_RATE_REDUCTION := 0.03

const BASE_MAX_HP := 100.0

const QUEST_DAILY_COUNT := 3
const QUEST_WEEKLY_COUNT := 2
const QUEST_MONTHLY_COUNT := 1
const QUEST_REFRESH_HOUR := 0

enum QuestType {
	KILL_ENEMIES,
	KILL_BOSSES,
	COMPLETE_WAVES,
	COLLECT_COINS,
	BUILD_TOWERS,
	USE_SKILLS,
	PERFECT_WAVES,
	REACH_WAVE,
	SPEND_COINS,
	UPGRADE_TOWERS
}

const QUEST_REWARD_DAILY_POINTS := 5
const QUEST_REWARD_WEEKLY_POINTS := 25
const QUEST_REWARD_MONTHLY_POINTS := 100
const QUEST_REWARD_MONTHLY_DIAMONDS := 2
const EMERALD_VALUE_IN_COINS := 100
const EMERALD_DROP_START_WAVE := 50
const EMERALD_DROP_CHANCE := 0.04
const DIAMOND_DROP_START_WAVE := 150
const DIAMOND_DROP_CHANCE := 0.001
const BOSS_EMERALD_REWARD_WAVE := 25
const BOSS_EMERALD_REWARD_COUNT := 20
const TOWER_UPGRADE_EMERALD_BASE_COST := 1
const TOWER_UPGRADE_EMERALD_SCALE := 1.2

const PRESTIGE_COST_REWARD_MULTIPLIER := 3
const PRESTIGE_COST_BASE_HP_BOOST := 8
const PRESTIGE_COST_HERO_DAMAGE_BOOST := 10
const PRESTIGE_COST_COIN_DROP_BOOST := 12
const PRESTIGE_COST_STARTING_COINS_BOOST := 15

const PRESTIGE_COST_TOWER_ARROW_CORROSIVE := 3
const PRESTIGE_COST_SLOW_TOWER_FROST := 3
const PRESTIGE_COST_AOE_TOWER_INFERNO := 3
const PRESTIGE_COST_SNIPER_TOWER_PIERCE := 3
const PRESTIGE_COST_SHOCK_TOWER_CHAIN := 3
const PRESTIGE_COST_BOOST_TOWER_AURA := 3

const BUTTON_HOVER_SCALE := 1.0
const BUTTON_HOVER_TRANSITION_TIME := 0.12
const BUTTON_PRESS_SCALE := 0.97
const BUTTON_PRESS_TRANSITION_TIME := 0.08

const BARRACKS_INITIAL_SPAWN_RATE := 3.0
const BARRACKS_MIN_SPAWN_RATE := 1.0
const BARRACKS_SPAWN_RATE_REDUCTION := 0.5
const BARRACKS_INITIAL_HOLD_TIME := 1.0
const BARRACKS_HOLD_TIME_INCREASE := 0.5
const BARRACKS_MAX_HOLD_TIME := 5.0
const BARRACKS_INITIAL_SOLDIER_DAMAGE := 0.5
const BARRACKS_INITIAL_PROJECTILE_SPEED := 80.0
const BARRACKS_PROJECTILE_SPEED_INCREASE := 20.0
const BARRACKS_SOLDIER_DAMAGE_INCREASE := 0.35

const SPECIAL_WAVE_INTERVAL := 10
const SPECIAL_WAVE_ALERT_DURATION := 2.0
const SPECIAL_WAVE_ALERT_FADE_OUT_START := 1.0
const BOSS_ALERT_DURATION := 4.0

const TALISMAN_SELL_PRICE_COMMON := 1
const TALISMAN_SELL_PRICE_UNCOMMON := 2
const TALISMAN_SELL_PRICE_RARE := 5
const TALISMAN_SELL_PRICE_EPIC := 10
const TALISMAN_SELL_PRICE_LEGENDARY := 25

const WEATHER_CHANGE_INTERVAL := 5
const WEATHER_DURATION_WAVES := 3
const WEATHER_RAIN_TOWER_DAMAGE_REDUCTION := 0.15
const WEATHER_RAIN_TOWER_RANGE_REDUCTION := 0.10
const WEATHER_HEAT_ENEMY_SPEED_BOOST := 1.25
const WEATHER_HEAT_ENEMY_HP_BOOST := 1.15
const WEATHER_FOG_VISIBILITY_REDUCTION := 0.20
const WEATHER_NIGHT_VISIBILITY_REDUCTION := 0.30
const WEATHER_NIGHT_ENEMY_SPEED_BOOST := 1.10

const MARKET_ITEM_HEAL_FULL := 40
const MARKET_ITEM_TOWER_DAMAGE_BOOST := 5
const MARKET_ITEM_HERO_DAMAGE_BOOST := 4
const MARKET_ITEM_EXTRA_LIFE := 20
const MARKET_ITEM_HERO_FIRERATE_UPGRADE := 150
const MARKET_ITEM_HERO_DUAL_CANNON := 150
